### ISSUE TITLE
Error when viewing new individual

### ISSUE THREAD

**Issue by godzil3** [hartenthaler/hh_extended_family#173]
Hi,

I created a person, not yet approved, when tryign to check unapproved profile i get following error

![obraz](https://github.com/hartenthaler/hh_extended_family/assets/45084859/0370b3e8-30c3-481f-b2cd-cedc47943178)

Undefined array key 1 …/modules_v4/hh_extended_family/src/Factory/Objects/ProbandName.php:122
#0 …/modules_v4/hh_extended_family/src/Factory/Objects/ProbandName.php(122): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}()
#1 …/modules_v4/hh_extended_family/src/Factory/Objects/ProbandName.php(99): Hartenthaler\Webtrees\Module\ExtendedFamily\ProbandName::findNiceNameFromNameParts()
#2 …/modules_v4/hh_extended_family/src/Factory/Objects/ProbandName.php(55): Hartenthaler\Webtrees\Module\ExtendedFamily\ProbandName::findNiceNameFromRufnameOrNameParts()
#3 …/modules_v4/hh_extended_family/ExtendedFamily.php(166): Hartenthaler\Webtrees\Module\ExtendedFamily\ProbandName::findNiceName()
#4 …/modules_v4/hh_extended_family/ExtendedFamilyPersonExists.php(71): Hartenthaler\Webtrees\Module\ExtendedFamily\ExtendedFamily->constructProband()
#5 …/modules_v4/hh_extended_family/ExtendedFamilyTabModule.php(126): Hartenthaler\Webtrees\Module\ExtendedFamily\ExtendedFamilyPersonExists->__construct()
#6 …/modules_v4/hh_extended_family/ExtendedFamilyTabModule.php(555): Hartenthaler\Webtrees\Module\ExtendedFamily\ExtendedFamilyTabModule->personExistsInExtendedFamily()
#7 …/resources/views/individual-page-tabs.phtml(20): Hartenthaler\Webtrees\Module\ExtendedFamily\ExtendedFamilyTabModule->isGrayedOut()
#8 …/app/View.php(183): include('...')
#9 …/app/View.php(278): Fisharebest\Webtrees\View->render()
#10 …/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make()
#11 …/modules_v4/webtrees-theme-modern/resources/views/individual-page-tabs.phtml(3): view()
#12 …/app/View.php(183): include('...')
#13 …/app/View.php(278): Fisharebest\Webtrees\View->render()
#14 …/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make()
#15 …/modules_v4/webtrees-theme-modern/resources/views/individual-page.phtml(121): view()
#16 …/app/View.php(183): include('...')
#17 …/app/View.php(278): Fisharebest\Webtrees\View->render()
#18 …/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make()
#19 …/app/Http/ViewResponseTrait.php(50): view()
#20 …/app/Http/RequestHandlers/IndividualPage.php(126): Fisharebest\Webtrees\Http\RequestHandlers\IndividualPage->viewResponse()
#21 …/app/Http/Middleware/RequestHandler.php(55): Fisharebest\Webtrees\Http\RequestHandlers\IndividualPage->handle()
#22 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler->process()
#23 …/modules_v4/vesta_research_suggestions/ResearchSuggestionsModule.php(277): Middleland\Dispatcher->handle()
#24 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Cissee\Webtrees\Module\ResearchSuggestions\ResearchSuggestionsModule->process()
#25 …/app/Module/HitCountFooterModule.php(154): Middleland\Dispatcher->handle()
#26 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process()
#27 …/app/Module/CheckForNewVersion.php(122): Middleland\Dispatcher->handle()
#28 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\CheckForNewVersion->process()
#29 …/app/Http/Middleware/CheckCsrf.php(80): Middleland\Dispatcher->handle()
#30 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process()
#31 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#32 …/app/Webtrees.php(275): Middleland\Dispatcher->dispatch()
#33 …/app/Http/Middleware/Router.php(163): Fisharebest\Webtrees\Webtrees::dispatch()
#34 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process()
#35 …/app/Http/Middleware/BootModules.php(60): Middleland\Dispatcher->handle()
#36 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process()
#37 …/app/Http/Middleware/RegisterGedcomTags.php(54): Middleland\Dispatcher->handle()
#38 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags->process()
#39 …/app/Http/Middleware/LoadRoutes.php(75): Middleland\Dispatcher->handle()
#40 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process()
#41 …/app/Http/Middleware/CheckForNewVersion.php(57): Middleland\Dispatcher->handle()
#42 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForNewVersion->process()
#43 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle()
#44 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}()
#45 …/app/Http/Middleware/UseTransaction.php(44): Illuminate\Database\Connection->transaction()
#46 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process()
#47 …/app/Http/Middleware/DoHousekeeping.php(73): Middleland\Dispatcher->handle()
#48 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process()
#49 …/app/Http/Middleware/UseTheme.php(69): Middleland\Dispatcher->handle()
#50 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process()
#51 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle()
#52 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process()
#53 …/app/Http/Middleware/UseLanguage.php(71): Middleland\Dispatcher->handle()
#54 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process()
#55 …/app/Http/Middleware/UseSession.php(78): Middleland\Dispatcher->handle()
#56 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process()
#57 …/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle()
#58 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process()
#59 …/app/Http/Middleware/UseDatabase.php(122): Middleland\Dispatcher->handle()
#60 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process()
#61 …/app/Http/Middleware/BadBotBlocker.php(287): Middleland\Dispatcher->handle()
#62 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process()
#63 …/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher->handle()
#64 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process()
#65 …/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle()
#66 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process()
#67 …/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle()
#68 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process()
#69 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process()
#70 …/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle()
#71 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process()
#72 …/app/Http/Middleware/BaseUrl.php(73): Middleland\Dispatcher->handle()
#73 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process()
#74 …/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle()
#75 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process()
#76 …/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle()
#77 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process()
#78 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle()
#79 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process()
#80 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#81 …/app/Webtrees.php(275): Middleland\Dispatcher->dispatch()
#82 …/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch()
#83 …/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest()
#84 {main}

**Comment by hartenthaler** [comment]
Thank you for reporting that! It is related to an error if a person does not have a name.

**Comment by gatonero** [comment]
Here you posted a working [working solution](https://www.webtrees.net/index.php/forum/help-for-release-2-1-x/37656-broken-entry-fix) in Jan 2023.

**Comment by hartenthaler** [comment]
This should be solved in the release I published yesterday.
